---

# File: group_vars/all/dims.yml

# This file is intended to serve as the principle site
# configuration file.

cronjobs:
  - name: 'dims.updatecheck'
    weekday: '*'
    hour: '6'
    minute: '0'
    user: 'ansible'
    job: '{{ dims_bin }}/dims.updatecheck'

yaml_mode_whitelist:
  - 'mode: push'
  - "{% raw %}mode: '{{ item.value.mode }}'{% endraw %}"

# Try to use this as the PATH set at the lowest level for shells, startup scripts,
# etc. This way there is more consistency across system components, so less chance
# for random failures or random behavior in scripts.
dims_global_path: '{{ dims_bin }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

dims_kibana_port: 8480
dims_ssh_port: 8422
dims_ssl_port: 8443
# TODO(dittrich): This is a confusing name (left over from old role)
dims_elasticsearch_kibana_port: 9200

# Default browser page
dims_kibana_url: 'http://localhost:{{ dims_kibana_port }}/#/dashboards/UFW_Data.json'
dims_owf_url: 'https://ops.local:{{ dims_ssl_port }}/owf/'
dims_firefox_default_homepage: '{{ dims_owf_url }}'

# file name of Vault password file. Path is created in Vagrantfile.
dims_vault_password_file: '{{ dims_private }}/vault_pass.txt'

dimscli_version: 0.26.0

dims_timezone: 'US/Pacific'
dims_locale: 'en_US.UTF-8'
dims_etcd2_reboot_strategy: 'off'


# Variables specific to creating host playbook for Ansible provisioning
remoteUser: '{{ ansible_user_id }}'

# Variables for running different Ansible roles
artifact_branch: 'develop'
install_type: 'install'
install_mode: 'system'

# Default to using a local squid proxy on the virtual machine host (e.g., dev laptop)
https_proxy: 'https://10.0.2.2:8000'

# Bash automated testing system
bats_version: 'v0.4.0'


# vim: ft=ansible :
