---

# File: playbooks/base_playbook.yml

# This is a generic base playbook that is used to run any specific
# role on demand, as opposed to creating a proliferation of specific
# playbooks, one per role.  For more on why and how you use this,
# see:
#  o "Graduating Past Playbooks: How to Use Ansible When Your
#    Infrastructure Grows Up," by Bob McQueen.
#     http://nylas.com/blog/graduating-past-playbooks
#  o Ansible Playbooks documentation, section "Running DIMS playbooks".
#
#  $ cd $GIT/ansible-dims-playbooks
#  $ ansible-playbook -e host=host.fq.dn -e role=hello playbooks/base_playbook.yml
#  $ cat /tmp/hello.txt
#  b52
#
# Alternately, pass a JSON object to -e as follows:
#  $ ansible-playbook -e "{'host': 'host.fq.dn', 'role': 'hello', \
#  > 'playbooks_root': '"$PBR"'}" playbooks/base_playbook.yml
#
# To invoke debugging, add "--tags debug" and "-v" ("-vv", "-vvv", ...)
#
# YOU MUST define at minimum the vars below. They are to be over-ridden
# using the precendence defined by Ansible for ansible and ansible-playbook
# command line programs. See Ansible documentation if you don't know what
# that means.

- name: Ansible 2.x Base Playbook
  vars:
   - playbooks_root: "{{ lookup('env', 'PBR') }}"
   - _debug: False
  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"
  hosts: "{{ host|default('localhost') }}" # override with '-e host=$host.fq.dn'
  gather_facts: True

# Everything from here on out will be stripped by dims.ansible-playbooks
# in order to use this as a base for inserting roles (--role) or
# tasks (--task). This playbook can still function stand-alone and
# be run directly using ansible-playbook as described above.
#
# @@dims.ansible-playbook@@
  pre_tasks:
    - name: Debugging
      include: "{{ tasks_path }}/debug-dump-vars.yml"
      when: _debug is defined and _debug|bool
      tags: [ debug ]

    - name: Include codename-specific variables
      include_vars:
        file: '{{ item }}'
      with_first_found:
        - files:
          - "{{ ansible_lsb.codename }}.yml"
          paths:
          - '{{ dims_private }}/vars'
          - ../vars

  roles:
  - "{{ role }}"

# vim: ft=ansible :
