---

# File: playbooks/hosts/red.devops.local.yml

- name: Configure host "red.devops.local"
  hosts: red.devops.local

  vars:
    playbooks_root: "{{ lookup('env', 'PBR') }}"

  vars_files:
   - "{{ playbooks_root }}/vars/global.yml"

  remote_user: "ansible"
  become: yes

  roles:
    - { role: debug }
    - { role: base }
    - { role: hosts }
    - { role: ansible-role-ca, ca_distribute_keys: true }
    - { role: nginx }
    - { role: dns, zones: ['local', 'consul'] }
    - { role: python-virtualenv, use_sphinx: false }
    - { role: rabbitmq }
    - { role: postfix }
    - { role: docker }
    - { role: consul }

  handlers:
   - include: "{{ handlers_path }}/restart_services.yml"

# vim: ft=ansible :
